global:
  version: 2.5.4
  serviceAccountName: vault-auth

  vault:
    type: disabled  # ✅ Désactivé car on n’utilise pas Vault

  cluster:
    provider: minikube  # ✅ Cluster local avec Minikube
    cloudNativeServices: false

  proxy:
    provider: "none"
    externalUrlSuffix: supplychain-net

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.supplychain-net:7054
    caAdminUser: supplychain-admin
    caAdminPassword: supplychain-adminpw
    orgName: supplychain
    type: peer
    componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"
  users: 
    usersList:
      - user:
          identity: user1
          attributes:
            - key: "hf.Revoker"
              value: "true"
  settings:
    createConfigMaps: true  # ✅ Important pour peer0 uniquement
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true

storage:
  enabled: true
  storageClass: "standard"
  size: 512Mi

peer:
  gossipPeerAddress:  # ✅ Vide pour peer0
  logLevel: info
  localMspId: supplychainMSP
  tlsStatus: true
  cliEnabled: false
  ordererAddress: orderer1.supplychain-net:7050
  builder: hyperledger/fabric-ccenv
  couchdb:
    username: supplychain-user
    password: supplychain-userpw
  upgrade: false
