global:
  serviceAccountName: vault-auth
  cluster:
    provider: minikube  
    cloudNativeServices: false
  vault:
    type: disabled  
  proxy:
    provider: none
    externalUrlSuffix: retailer-net  # ✅ CORRECTED to retailer-net

storage:
  storageClass: "standard"  
  size: 512Mi

server:
  removeCertsOnDelete: true
  tlsStatus: true
  adminUsername: retailer-admin  # ✅ CORRECTED to retailer-admin
  adminPassword: retailer-adminpw  # ✅ CORRECTED to retailer-adminpw
  subject: "/C=GB/ST=London/L=London/O=Retailer"  # ✅ CORRECTED to Retailer
