# Updated Helm values for fabric-peer in Minikube (carrier network)
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  vault:
    type: disabled  # Disabled Vault

  cluster:
    provider: minikube  # Changed from "azure" to "minikube"
    cloudNativeServices: false

  proxy:
    provider: "none"
    externalUrlSuffix: carrier-net

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.carrier-net:7054
    caAdminUser: carrier-admin
    caAdminPassword: carrier-adminpw
    orgName: carrier
    type: peer
    componentSubject: "O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB"
  users: 
    usersList:
      - user:
        identity: user1
        attributes:
        - key: "hf.Revoker"
          value: "true"
  settings:
    # This must be set to true when installing the first peer in the organization
    createConfigMaps: true
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true

storage:
  enabled: true  # Enabled persistent storage for Minikube
  storageClass: "standard"  # Ensure Minikube uses its default storage
  size: 512Mi  # Adjust storage size as needed

peer:
  gossipPeerAddress: 
  logLevel: info
  localMspId: carrierMSP
  tlsStatus: true
  cliEnabled: true
  ordererAddress: orderer1.supplychain-net:7050
  builder: hyperledger/fabric-ccenv
  couchdb:
    username: carrier-user
    password: carrier-userpw
  upgrade: false
