# Updated Helm values for fabric-genesis in Minikube (supplychain network)
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  cluster:
    provider: minikube  
    cloudNativeServices: false
  vault:
    type: disabled  
  proxy:
    provider: none
    externalUrlSuffix: supplychain-net

organizations:
  - name: supplychain
    orderers:
      - name: orderer1
        ordererAddress: orderer1.supplychain-net:7050 
      - name: orderer2
        ordererAddress: orderer2.supplychain-net:7050
      - name: orderer3
        ordererAddress: orderer3.supplychain-net:7050
    peers:
      - name: peer1
        peerAddress: peer1.supplychain-net:7051
      - name: peer2
        peerAddress: peer2.supplychain-net:7051

  - name: carrier
    peers:
      - name: peer0
        peerAddress: peer0.carrier-net:7051 

  - name: retailer  # ✅ Added retailer-net
    peers:
      - name: peer3
        peerAddress: peer3.retailer-net:7051 

consensus: raft
channels:
  - name: allchannel
    consortium: SupplyChainConsortium
    orderers:
      - supplychain
    participants:
      - supplychain
      - carrier
      - retailer  # ✅ Added retailer-net as a participant

settings:
  removeConfigMapOnDelete: true
