---
global:
  version: 2.5.4
  serviceAccountName: vault-auth  
  cluster:
    provider: minikube  
    cloudNativeServices: false
  vault:
    type: disabled  

peer:
  name: peer3  # ✅ Changed for retailer
  type: anchor
  address: peer3.retailer-net:7051  # ✅ Changed for retailer-net
  localMspId: retailerMSP  # ✅ Changed for retailer
  logLevel: info
  tlsStatus: true
  channelName: allchannel  # ✅ Ensure this matches the channel name
  ordererAddress: orderer1.supplychain-net:7050  # ✅ Same orderer for all
