# Updated Helm values for fabric-orderernode in Minikube (supplychain network)
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  vault:
    type: disabled  # Disabled Vault

  cluster:
    provider: minikube  # Changed from "azure" to "minikube"
    cloudNativeServices: false
  
  proxy:
    provider: none
    externalUrlSuffix: supplychain-net

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.supplychain-net:7054
    caAdminUser: supplychain-admin
    caAdminPassword: supplychain-adminpw
    orgName: supplychain
    type: orderer
    componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"
  settings:
    # Flag to create configmaps for the organization. This must be true for the first orderer/peer in the organization.
    createConfigMaps: true
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true

orderer:
  consensus: raft
  logLevel: info
  localMspId: supplychainMSP
  tlsstatus: true
