apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: supplychain-net
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    password_file /mosquitto/config/passwords.txt
