apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: supplychain-net
spec:
  selector:
    app: mosquitto
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto2
  namespace: supplychain-net
spec:
  selector:
    app: mosquitto2
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
