apiVersion: v1
kind: Service
metadata:
  name: blockchain-agent-service
  namespace: supplychain-net
spec:
  selector:
    app: blockchain-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
