apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-agent
  namespace: supplychain-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-agent
  template:
    metadata:
      labels:
        app: blockchain-agent
    spec:
      containers:
        - name: blockchain-agent
          image: mmdtsp/mmd-blockchain-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # === CA ===
            - name: HYPERLEDGER_CA_ADDRESS
              value: "ca.supplychain-net.svc.cluster.local:7054"
            # === Gateway A ===
            - name: GATEWAY_A_HOST
              value: "mosquitto1.supplychain-net.svc.cluster.local"
            - name: GATEWAY_A_PORT
              value: "1883"
            - name: GATEWAY_A_USERNAME
              value: "user1"
            - name: GATEWAY_A_PASSWORD
              value: "mmd1"

            # === Gateway B ===
            - name: GATEWAY_B_HOST
              value: "mosquitto2.supplychain-net.svc.cluster.local"
            - name: GATEWAY_B_PORT
              value: "1883"
            - name: GATEWAY_B_USERNAME
              value: "user1"
            - name: GATEWAY_B_PASSWORD
              value: "mmd1"
          volumeMounts:
            - name: ca-cert
              mountPath: /test-network/organizations/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
              readOnly: true
            - name: wallet-storage
              mountPath: /wallet
            - name: connection-profile
              mountPath: /test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml
              subPath: connection-org1.yaml
              readOnly: true  
      volumes:
        - name: ca-cert
          secret:
            secretName: blockchain-agent-ca-cert
        - name: wallet-storage
          emptyDir: {}
        - name: connection-profile
          configMap:
            name: connection-org1
            items:
              - key: connection-org1.yaml
                path: connection-org1.yaml  
