apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-agent
  namespace: supplychain-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-agent
  template:
    metadata:
      labels:
        app: blockchain-agent
    spec:
      containers:
        - name: blockchain-agent
          image: mmdtsp/mmd-blockchain-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # === Gateway A ===
            - name: GATEWAY_A_HOST
              value: "mosquitto1.supplychain-net.svc.cluster.local"
            - name: GATEWAY_A_PORT
              value: "1883"
            - name: GATEWAY_A_USERNAME
              value: "user1"
            - name: GATEWAY_A_PASSWORD
              value: "mmd1"

            # === Gateway B ===
            - name: GATEWAY_B_HOST
              value: "mosquitto2.supplychain-net.svc.cluster.local"
            - name: GATEWAY_B_PORT
              value: "1883"
            - name: GATEWAY_B_USERNAME
              value: "user1"
            - name: GATEWAY_B_PASSWORD
              value: "mmd1"
